using FluentAssertions;
using RuinaRPG.Domain.Auth;

namespace RuinaRPG.Tests.Unit.Auth;

public class JwtClaimsParserTests
{
    // header {"alg":"HS256","typ":"JWT"}, payload {"sub":"a1b2c3d4-0000-0000-0000-000000000001","role":"GM","nickname":"Testador","exp":9999999999}
    // — independently base64url-encoded outside this codebase, not generated by the code under test.
    private const string ValidToken =
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMWIyYzNkNC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDEiLCJyb2xlIjoiR00iLCJuaWNrbmFtZSI6IlRlc3RhZG9yIiwiZXhwIjo5OTk5OTk5OTk5fQ.dGVzdC1zaWduYXR1cmU";

    [Fact]
    public void ParsePayload_extracts_sub_role_and_nickname_from_a_valid_token()
    {
        var claims = JwtClaimsParser.ParsePayload(ValidToken);

        claims["sub"].Should().Be("a1b2c3d4-0000-0000-0000-000000000001");
        claims["role"].Should().Be("GM");
        claims["nickname"].Should().Be("Testador");
    }

    [Fact]
    public void ParsePayload_throws_FormatException_for_a_token_with_the_wrong_number_of_segments()
    {
        var act = () => JwtClaimsParser.ParsePayload("not-a-jwt");

        act.Should().Throw<FormatException>();
    }

    [Fact]
    public void ParsePayload_throws_for_a_payload_segment_that_is_not_valid_base64url()
    {
        var act = () => JwtClaimsParser.ParsePayload("header.not!!valid!!base64url.signature");

        act.Should().Throw<FormatException>();
    }
}
