// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RuinaRPG.Infrastructure.Persistence;

#nullable disable

namespace RuinaRPG.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RuinaRpgDbContext))]
    [Migration("20260822220342_AddTraits")]
    partial class AddTraits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Campaigns.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GmId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GmId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Campaigns.CampaignMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CampaignId", "UserId")
                        .IsUnique();

                    b.ToTable("CampaignMembers");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterAffinity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaminhoNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CharacterSheetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Elemento")
                        .HasColumnType("integer");

                    b.Property<int>("Experiencia")
                        .HasColumnType("integer");

                    b.Property<int>("SubElemento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSheetId");

                    b.ToTable("CharacterAffinities");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterArmorSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterSheetId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DurabilidadeAtual")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("CharacterSheetId", "Slot")
                        .IsUnique();

                    b.ToTable("CharacterArmorSlots");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterSheetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactItemId");

                    b.HasIndex("CharacterSheetId");

                    b.ToTable("CharacterArtifacts");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Atributo")
                        .HasColumnType("integer");

                    b.Property<int>("Bonus")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterSheetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Gasto")
                        .HasColumnType("integer");

                    b.Property<bool>("TemMaestria")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSheetId", "Atributo")
                        .IsUnique();

                    b.ToTable("CharacterAttributes");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterSheetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qtd")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSheetId");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterInventoryItems");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterMastery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Atributo")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterSheetId")
                        .HasColumnType("uuid");

                    b.Property<int>("GastoMaestria")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pericia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSheetId");

                    b.ToTable("CharacterMasteries");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterRune", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterSheetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Grau")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSheetId");

                    b.ToTable("CharacterRunes");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdrenalinaAtual")
                        .HasColumnType("integer");

                    b.Property<int?>("Afinidade")
                        .HasColumnType("integer");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ciclos")
                        .HasColumnType("integer");

                    b.Property<int>("Circulo")
                        .HasColumnType("integer");

                    b.Property<int>("Cobertura")
                        .HasColumnType("integer");

                    b.Property<int>("EAPAtual")
                        .HasColumnType("integer");

                    b.Property<int>("EstresseAtual")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienciaAtual")
                        .HasColumnType("integer");

                    b.Property<int>("FocoAtual")
                        .HasColumnType("integer");

                    b.Property<int>("Grau")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LastDismissedLevelUpLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("Linhagem")
                        .HasColumnType("integer");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int>("NucleosRankA")
                        .HasColumnType("integer");

                    b.Property<int>("NucleosRankB")
                        .HasColumnType("integer");

                    b.Property<int>("NucleosRankC")
                        .HasColumnType("integer");

                    b.Property<int>("NucleosRankD")
                        .HasColumnType("integer");

                    b.Property<int>("NucleosRankE")
                        .HasColumnType("integer");

                    b.Property<int>("NucleosRankF")
                        .HasColumnType("integer");

                    b.Property<int>("NucleosRankS")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("PontosDeIgnicaoAtual")
                        .HasColumnType("integer");

                    b.Property<int>("PontosDeIgnicaoTotal")
                        .HasColumnType("integer");

                    b.Property<bool>("PossuiCoracaoDeMana")
                        .HasColumnType("boolean");

                    b.Property<string>("Propriedade")
                        .HasColumnType("text");

                    b.Property<string>("SubVocacao")
                        .HasColumnType("text");

                    b.Property<int?>("Variante")
                        .HasColumnType("integer");

                    b.Property<int>("VitalidadeAtual")
                        .HasColumnType("integer");

                    b.Property<int?>("Vocacao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ImageId");

                    b.HasIndex("OwnerId");

                    b.ToTable("CharacterSheets");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterShield", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterSheetId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurabilidadeAtual")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSheetId");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterShields");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterSheetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Gasto")
                        .HasColumnType("integer");

                    b.Property<int>("Pericia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSheetId", "Pericia")
                        .IsUnique();

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterSpellAbility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterSheetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Custo")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GastoEmPI")
                        .HasColumnType("integer");

                    b.Property<int>("Grau")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceBankEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSheetId");

                    b.ToTable("CharacterSpellAbilities");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterSpellAbilityEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterSpellAbilityId")
                        .HasColumnType("uuid");

                    b.Property<int>("CustoPI")
                        .HasColumnType("integer");

                    b.Property<string>("EfeitoNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSpellAbilityId");

                    b.ToTable("CharacterSpellAbilityEffects");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterWeapon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterSheetId")
                        .HasColumnType("uuid");

                    b.Property<int>("DurabilidadeAtual")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSheetId");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterWeapons");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Diary.DiaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CharacterSheetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSecretNote")
                        .HasColumnType("boolean");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("CampaignId");

                    b.ToTable("DiaryEntries");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Diary.DiaryEntryImage", b =>
                {
                    b.Property<Guid>("DiaryEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid");

                    b.HasKey("DiaryEntryId", "ImageId");

                    b.HasIndex("ImageId");

                    b.ToTable("DiaryEntryImages");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Diary.DiaryEntryRecipient", b =>
                {
                    b.Property<Guid>("DiaryEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("DiaryEntryId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("DiaryEntryRecipients");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("InvitedByGmId")
                        .HasColumnType("uuid");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedNickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedNickname")
                        .IsUnique();

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Images.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Invites.InviteCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GmId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RedeemedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("GmId");

                    b.HasIndex("RedeemedByUserId");

                    b.ToTable("InviteCodes");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GmId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric");

                    b.Property<int>("Preco")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("GmId");

                    b.HasIndex("ImageId");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Tipo").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Rules.Trait", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Custo")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Polaridade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Traits");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.SpellsAndAbilities.SpellAbilityBankEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CustoPI")
                        .HasColumnType("integer");

                    b.Property<string>("EfeitoNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpellAbilityBankEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpellAbilityBankEntryId");

                    b.ToTable("SpellAbilityBankEffects");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.SpellsAndAbilities.SpellAbilityBankEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Custo")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GastoEmPI")
                        .HasColumnType("integer");

                    b.Property<Guid>("GmId")
                        .HasColumnType("uuid");

                    b.Property<int>("Grau")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GmId");

                    b.ToTable("SpellAbilityBankEntries");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Items.Arma", b =>
                {
                    b.HasBaseType("RuinaRPG.Infrastructure.Items.Item");

                    b.Property<int?>("Alcance")
                        .HasColumnType("integer");

                    b.Property<string>("Critico")
                        .HasColumnType("text");

                    b.Property<string>("Dados")
                        .HasColumnType("text");

                    b.Property<int?>("Dano")
                        .HasColumnType("integer");

                    b.Property<int?>("DurabilidadeMaxima")
                        .HasColumnType("integer");

                    b.Property<int?>("Empunhadura")
                        .HasColumnType("integer");

                    b.Property<string>("RequisitoAtributo")
                        .HasColumnType("text");

                    b.Property<string>("Subcategoria")
                        .HasColumnType("text");

                    b.Property<int?>("Tier")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoDeDano")
                        .HasColumnType("integer");

                    b.ToTable("Items", t =>
                        {
                            t.Property("DurabilidadeMaxima")
                                .HasColumnName("Arma_DurabilidadeMaxima");
                        });

                    b.HasDiscriminator().HasValue("Arma");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Items.Armadura", b =>
                {
                    b.HasBaseType("RuinaRPG.Infrastructure.Items.Item");

                    b.Property<int?>("Categoria")
                        .HasColumnType("integer");

                    b.Property<int?>("Defesa")
                        .HasColumnType("integer");

                    b.Property<int?>("DurabilidadeMaxima")
                        .HasColumnType("integer");

                    b.Property<string>("Penalidade")
                        .HasColumnType("text");

                    b.Property<int?>("RF")
                        .HasColumnType("integer");

                    b.Property<int?>("RM")
                        .HasColumnType("integer");

                    b.Property<int?>("RequisitoVigor")
                        .HasColumnType("integer");

                    b.ToTable("Items", t =>
                        {
                            t.Property("Categoria")
                                .HasColumnName("Armadura_Categoria");

                            t.Property("DurabilidadeMaxima")
                                .HasColumnName("Armadura_DurabilidadeMaxima");

                            t.Property("Penalidade")
                                .HasColumnName("Armadura_Penalidade");

                            t.Property("RequisitoVigor")
                                .HasColumnName("Armadura_RequisitoVigor");
                        });

                    b.HasDiscriminator().HasValue("Armadura");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Items.Artefato", b =>
                {
                    b.HasBaseType("RuinaRPG.Infrastructure.Items.Item");

                    b.Property<string>("Alvo")
                        .HasColumnType("text");

                    b.Property<int?>("TipoDeAlvo")
                        .HasColumnType("integer");

                    b.Property<int?>("Valor")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Artefato");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Items.Escudo", b =>
                {
                    b.HasBaseType("RuinaRPG.Infrastructure.Items.Item");

                    b.Property<int?>("BonusDefesa")
                        .HasColumnType("integer");

                    b.Property<int?>("Categoria")
                        .HasColumnType("integer");

                    b.Property<int?>("DurabilidadeMaxima")
                        .HasColumnType("integer");

                    b.Property<string>("Penalidade")
                        .HasColumnType("text");

                    b.Property<int?>("RequisitoVigor")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Escudo");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Items.ItemGeral", b =>
                {
                    b.HasBaseType("RuinaRPG.Infrastructure.Items.Item");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Subcategoria")
                        .HasColumnType("text");

                    b.ToTable("Items", t =>
                        {
                            t.Property("Subcategoria")
                                .HasColumnName("ItemGeral_Subcategoria");
                        });

                    b.HasDiscriminator().HasValue("ItemGeral");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuinaRPG.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Campaigns.Campaign", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("GmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Campaigns.CampaignMember", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.Campaigns.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuinaRPG.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterAffinity", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.CharacterSheets.CharacterSheet", null)
                        .WithMany()
                        .HasForeignKey("CharacterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterArmorSlot", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.CharacterSheets.CharacterSheet", null)
                        .WithMany()
                        .HasForeignKey("CharacterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuinaRPG.Infrastructure.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterArtifact", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ArtifactItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RuinaRPG.Infrastructure.CharacterSheets.CharacterSheet", null)
                        .WithMany()
                        .HasForeignKey("CharacterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterAttribute", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.CharacterSheets.CharacterSheet", null)
                        .WithMany()
                        .HasForeignKey("CharacterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterInventoryItem", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.CharacterSheets.CharacterSheet", null)
                        .WithMany()
                        .HasForeignKey("CharacterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuinaRPG.Infrastructure.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterMastery", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.CharacterSheets.CharacterSheet", null)
                        .WithMany()
                        .HasForeignKey("CharacterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterRune", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.CharacterSheets.CharacterSheet", null)
                        .WithMany()
                        .HasForeignKey("CharacterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterSheet", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.Campaigns.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuinaRPG.Infrastructure.Images.Image", null)
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RuinaRPG.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterShield", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.CharacterSheets.CharacterSheet", null)
                        .WithMany()
                        .HasForeignKey("CharacterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuinaRPG.Infrastructure.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterSkill", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.CharacterSheets.CharacterSheet", null)
                        .WithMany()
                        .HasForeignKey("CharacterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterSpellAbility", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.CharacterSheets.CharacterSheet", null)
                        .WithMany()
                        .HasForeignKey("CharacterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterSpellAbilityEffect", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.CharacterSheets.CharacterSpellAbility", null)
                        .WithMany("Efeitos")
                        .HasForeignKey("CharacterSpellAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterWeapon", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.CharacterSheets.CharacterSheet", null)
                        .WithMany()
                        .HasForeignKey("CharacterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuinaRPG.Infrastructure.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Diary.DiaryEntry", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuinaRPG.Infrastructure.Campaigns.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Diary.DiaryEntryImage", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.Diary.DiaryEntry", null)
                        .WithMany()
                        .HasForeignKey("DiaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuinaRPG.Infrastructure.Images.Image", null)
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Diary.DiaryEntryRecipient", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.Diary.DiaryEntry", null)
                        .WithMany()
                        .HasForeignKey("DiaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuinaRPG.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Images.Image", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Invites.InviteCode", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("GmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuinaRPG.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RedeemedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.Items.Item", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("GmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuinaRPG.Infrastructure.Images.Image", null)
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.SpellsAndAbilities.SpellAbilityBankEffect", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.SpellsAndAbilities.SpellAbilityBankEntry", null)
                        .WithMany("Efeitos")
                        .HasForeignKey("SpellAbilityBankEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.SpellsAndAbilities.SpellAbilityBankEntry", b =>
                {
                    b.HasOne("RuinaRPG.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("GmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.CharacterSheets.CharacterSpellAbility", b =>
                {
                    b.Navigation("Efeitos");
                });

            modelBuilder.Entity("RuinaRPG.Infrastructure.SpellsAndAbilities.SpellAbilityBankEntry", b =>
                {
                    b.Navigation("Efeitos");
                });
#pragma warning restore 612, 618
        }
    }
}
